### ISSUE TITLE
Sales.exe demo crashes

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/MonitoringDemo#19]
> Application: Sales.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException
>
> Exception Info: System.IO.FileLoadException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Reflection.Assembly.LoadFrom(System.String)
   at NServiceBus.Hosting.Helpers.AssemblyScanner.TryLoadScannableAssembly(System.String, NServiceBus.Hosting.Helpers.AssemblyScannerResults, System.Collections.Generic.Dictionary`2<System.String,Boolean>, System.Reflection.Assembly ByRef)
>
> Exception Info: System.Exception
   at NServiceBus.Hosting.Helpers.AssemblyScanner.TryLoadScannableAssembly(System.String, NServiceBus.Hosting.Helpers.AssemblyScannerResults, System.Collections.Generic.Dictionary`2<System.String,Boolean>, System.Reflection.Assembly ByRef)
   at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies()
   at NServiceBus.EndpointConfiguration.GetAllowedTypes(System.String)
   at NServiceBus.EndpointConfiguration.Build()
   at NServiceBus.Endpoint.Create(NServiceBus.EndpointConfiguration)
   at NServiceBus.Endpoint+<Start>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetResult()
   at Sales.Program+<Main>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Sales.Program.<Main>(System.String[])

**Comment by WilliamBZA** [comment]
Probably the same problem as #20

Pre-requisites installed, and not much else. It's a fairly new install of windows.

**Comment by WilliamBZA** [comment]
I had to open the solution sln and compile the application myself once in order to get this to work. Even after "unblocking" the archive I still had the problem. I then added `<loadFromRemoteSources enabled="true"/>` to the `runtime` section of the app.config and still had the same problem. Eventually I opened the sln and compiled myself once and then reran the demo. It worked after that.

**Comment by tmasternak** [comment]
https://github.com/Particular/MonitoringDemo/pull/25
