### ISSUE TITLE
ServiceControl.exe demo crashes

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/MonitoringDemo#20]
> Application: ServiceControl.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException
>
> Exception Info: System.IO.FileLoadException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Reflection.Assembly.LoadFrom(System.String)
   at NServiceBus.Hosting.Helpers.AssemblyScanner.ScanAssembly(System.String, NServiceBus.Hosting.Helpers.AssemblyScannerResults)
   at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies()
   at NServiceBus.AllAssemblies.GetEnumerator()
   at System.Linq.Buffer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToArray[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at NServiceBus.BusConfiguration.AssembliesToScan(System.Collections.Generic.IEnumerable`1<System.Reflection.Assembly>)
   at Particular.ServiceControl.Bootstrapper.Initialize()
   at Particular.ServiceControl.Bootstrapper..ctor(System.ServiceProcess.ServiceBase)
   at Particular.ServiceControl.Hosting.Host.OnStart(System.String[])
   at Particular.ServiceControl.Hosting.Host.RunInteractive()
   at Particular.ServiceControl.Hosting.Host.Run(Boolean)
   at Particular.ServiceControl.Commands.RunCommand.RunAndWait(Particular.ServiceControl.Hosting.HostArguments)
   at Particular.ServiceControl.Commands.RunCommand.Execute(Particular.ServiceControl.Hosting.HostArguments)
   at Particular.ServiceControl.Commands.CommandRunner.Execute(Particular.ServiceControl.Hosting.HostArguments)
   at Particular.ServiceControl.Program.Main(System.String[])

**Comment by WilliamBZA** [comment]
Probably the same problem as #19 

Pre-requisites installed, and not much else. It's a fairly new install of windows.

**Comment by WilliamBZA** [comment]
This is due to windows defender blocking downloaded files. Even after "unblocking" the archive I still had the problem and the only resolution was to add `<loadFromRemoteSources enabled="true"/>` to the `runtime` section of the app.config.

Perhaps this should be added to the config sections of all the files as a precaution?

**Comment by tmasternak** [comment]
Solved in #23
